# Site settings
title: Teach Me To Code
description: "The neverending story of how I learned to code."
url: "http://christopherfujino.github.io"
author:
  name: "Christopher Fujino"
  email: "christopherfujino@gmail.com"
  url: "http://christopherfujino.github.io"

# Build settings
baseurl: "/" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 6
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
